site:
  title: ML4IoT
  url: https://ml4iot.appuioapp.ch
  start_page: fj::index.adoc
  keys:
    google_analytics: ''
content:
  sources:
  - url: .                 # The current folder is a git repo
    branches: HEAD         # "HEAD" uses whichever branch is currently checked out
    start_path: docs
    edit_url: 'https://git.vshn.net/vshn/ml4iot/edit/develop/{path}'
ui:
  bundle:

    url: ./docs/ui-bundle.zip

    snapshot: false

runtime:
  cache_dir: ./.cache/antora

asciidoc:
  attributes:
    page-pagination: ''
    hide-uri-scheme: ''
    experimental: ''
    stem: ''
    icons: font
    kroki-server-url: https://kroki.vshn.net/
    kroki-fetch-diagram: ''
  extensions:
  - asciidoctor-kroki
output:
  destinations:
  - provider: fs
    path: ./_public
    clean: true

